version: '3.4'

services:
  cloud-eng-ping-pong-gamemanager:
    image: cloudengnl/ping-pong-gamemanager
    build:
      context: .
      dockerfile: src/CloudEng.PingPong.GameManager/Dockerfile
    ports:
      - "54000:50001"
    depends_on:
      - redis
      - placement
      - cloud-eng-pingpong-player-a
    networks:
      - cloud-eng-ping-pong-ntwrk

  cloud-eng-ping-pong-gamemanager-dapr:
    image: "daprio/daprd:1.0.0"
    command: ["./daprd", 
        "-app-id", "cloud-eng-ping-pong-gamemanager", 
        "-app-port", "80",
        "-placement-host-address", "placement:50006",
        "-components-path", "/components"
    ]
    volumes:
      - "./infrastructure/components:/components:ro"
    depends_on:
      - cloud-eng-ping-pong-gamemanager
    network_mode: "service:cloud-eng-ping-pong-gamemanager"

  cloud-eng-pingpong-player-a:
    image: cloudengnl/pingpong-player
    build:
      context: .
      dockerfile: src/CloudEng.PingPong.Player/Dockerfile
    ports:
      - "53000:50001"
    environment:
        - PlayerName=player-a
    depends_on:
      - redis
      - placement
    networks:
      - cloud-eng-ping-pong-ntwrk


  cloud-eng-pingpong-player-a-dapr:
    image: "daprio/daprd:1.0.0"
    command: ["./daprd", 
        "-app-id", "cloud-eng-pingpong-player-a", 
        "-app-port", "80",
        "-placement-host-address", "placement:50006",
        "-components-path", "/components"
    ]
    volumes:
      - "./infrastructure/components:/components:ro"
    depends_on:
      - cloud-eng-pingpong-player-a
    network_mode: "service:cloud-eng-pingpong-player-a"

  # External services
  redis:
    image: "redis:6.2.0-alpine"
    ports:
      - "6379"
    networks:
      - cloud-eng-ping-pong-ntwrk

  dashboard:
    image: daprio/dashboard:0.6.0
    ports:
      - "8085:8080"
    volumes:
      - "./infrastructure/components:/home/nonroot/.dapr/components:ro"
    networks:
     - cloud-eng-ping-pong-ntwrk

  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
    networks:
      - cloud-eng-ping-pong-ntwrk

networks:
  cloud-eng-ping-pong-ntwrk:
    driver: bridge