version: '3.4'
services:
  cloud-eng-ping-pong-gamemanager:
    environment:
      - ASPNETCORE_URLS=http://+:80

  cloud-eng-pingpong-player-a:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80