apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: game-messaging
spec:
  type: pubsub.redis
  version: v1
  metadata:
    - name: redisHost
      value: redis:6379
    - name: redisPassword
      value: ""
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: game-store
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: redis:6379
    - name: redisPassword
      value: ""
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: player-state-store
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: redis:6379
    - name: redisPassword
      value: ""