name: Build Project

on: push

jobs:
  build_project:
    name: Build Project
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        name: Checkoud code
      - name: Build Solution
        run: dotnet build -c Release --nologo -v q CloudEng.PingPong.sln
      - name: Run Unit-Tests
        run: dotnet build -c Release --nologo -v q CloudEng.PingPong.sln
