name: Build Project

on: push

jobs:
  build_project:
    name: Build Project
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        name: Checkout code
      - name: Build Solution in Debug configuration
        run: dotnet build -c Debug --nologo -v q CloudEng.PingPong.sln
      - name: Run Unit-Tests
        run: dotnet test -c Debug --nologo -v q CloudEng.PingPong.sln
  
  build_docker_image_player:
    name: Build Player Docker image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        name: Checkout code
      - run: docker build -f src/CloudEng.PingPong.Player/Dockerfile . -t  cloudengnl/pingpong-player:0.0.${{ github.run_number }}
        name: build Player image
      - name: Upload image
        uses: ishworkh/docker-image-artifact-upload@v1
        with:
          image: "cloudengnl/pingpong-player:0.0.${{ github.run_number }}"
        
  build_docker_image_game_manager:
    name: Build Game Manager Docker image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        name: Checkout code
      - run: docker build -f src/CloudEng.PingPong.GameManager/Dockerfile . -t  cloudengnl/ping-pong-gamemanager:0.0.${{ github.run_number }}
        name: build GameManager image
      - name: Upload image
        uses: ishworkh/docker-image-artifact-upload@v1
        with:
          image: "cloudengnl/ping-pong-gamemanager:0.0.${{ github.run_number }}"
          
  public_docker_images:
    name: Publish Docker images
    runs-on: ubuntu-20.04
    needs: [build_project, build_docker_image_player, build_docker_image_game_manager ]
    steps:
      - name: Download Player image
        uses: ishworkh/docker-image-artifact-download@v1
        with:
          image: "cloudengnl/pingpong-player:0.0.${{ github.run_number }}"
      - name: Download GameManager image
        uses: ishworkh/docker-image-artifact-download@v1
        with:
          image: "cloudengnl/ping-pong-gamemanager:0.0.${{ github.run_number }}"       
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_API_KEY }}  
      - run: docker image push --all-tags cloudengnl/ping-pong-gamemanager:0.0.${{ github.run_number }}